CREATE DATABASE EMPLOYEEMANAGEMENTSYSTEM;

 CREATE TABLE Department (dept_id INT PRIMARY KEY,dept_name VARCHAR(50));

CREATE TABLE Employee (emp_id INT PRIMARY KEY,emp_name VARCHAR(50),salary DECIMAL(10, 2),hire_date DATE,dept_id INT,FOREIGN KEY (dept_id) REFERENCES Department(dept_id));

INSERT INTO Department VALUES 
(1, 'HR'),
(2, 'Finance'),
(3, 'IT'),
(4, 'Marketing');

INSERT INTO Employee VALUES 
(101, 'Alice', 55000, '2022-01-15', 1),
(102, 'Bob', 67000, '2023-04-10', 2),
(103, 'Charlie', 45000, '2021-11-01', 3),
(104, 'David', 72000, '2024-02-25', 2),
(105, 'Eve', 38000, '2022-09-30', 1),
(106, 'Frank', 61000, '2023-06-10', 3);

INSERT INTO EMPLOYEE VALUE(107,'GEORGE',50000,'2024-07-01',3);

UPDATE EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID SET EMPLOYEE.SALARY=SALARY*1.10 WHERE DEPT_NAME = 'IT';

UPDATE EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID SET SALARY = SALARY * 1.10 WHERE DEPT_ID = 'IT';

DELETE FROM EMPLOYEE WHERE EMP_ID=106;

SELECT * FROM EMPLOYEE;

SELECT EMPLOYEE.EMP_NAME,DEPARTMENT.DEPT_NAME FROM EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID;

SELECT * FROM EMPLOYEE WHERE SALARY = 50000;

SELECT EMP_NAME,DEPT_NAME FROM EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID WHERE DEPT_NAME = 'FINANCE' OR 'HR';

SELECT * FROM EMPLOYEE WHERE HIRE_DATE BETWEEN '2020-01-01' AND '2023-12-21';

SELECT EMP_NAME,HIRE_DATE FROM EMPLOYEE WHERE DEPT_ID = 3;

SELECT EMP_NAME FROM EMPLOYEE WHERE EMP_NAME LIKE 'A%';

SELECT DEPARTMENT.DEPT_NAME,COUNT(EMPLOYEE.EMP_ID) FROM DEPARTMENT JOIN EMPLOYEE ON DEPARTMENT.DEPT_ID = EMPLOYEE.DEPT_ID GROUP BY DEPT_NAME ORDER BY EMP_ID;

SELECT SALARY FROM EMPLOYEE WHERE SALARY=(SELECT MAX(SALARY) FROM EMPLOYEE WHERE SALARY<(SELECT MAX(SALARY) FROM EMPLOYEE));

SELECT EMP_NAME,MAX(SALARY) FROM EMPLOYEE GROUP BY EMP_NAME ORDER BY SALARY DESC LIMIT 1;

SELECT EMPLOYEE.EMP_NAME,DEPARTMENT.DEPT_ID FROM EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID;

SELECT EMP_NAME,SALARY FROM EMPLOYEE WHERE SALARY BETWEEN 40000 AND 70000;

SELECT EMP_NAME FROM EMPLOYEE WHERE NOT DEPT_ID IN (3 OR 1);

SELECT * FROM EMPLOYEE WHERE HIRE_DATE < '2023-01-01';

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID WHERE DEPT_NAME = 'MARKETING';

UPDATE EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID SET SALARY = SALARY * 2000 WHERE DEPT_NAME = 'MARKETING';

SELECT EMP_NAME FROM EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID WHERE DEPT_NAME LIKE 'F%';

DELETE FROM EMPLOYEE WHERE SALARY<40000;

SELECT EMP_NAME AS EMPLOYEES, DEPT_NAME AS DEPARTMENTS FROM EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID;

SELECT EMPLOYEE.EMP_NAME,AVG(EMPLOYEE.SALARY),DEPARTMENT.DEPT_NAME FROM EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID GROUP BY DEPT_NAME ;

SELECT AVG(EMPLOYEE.SALARY) AS HIGHESTAVGSALARY,DEPARTMENT.DEPT_NAME FROM EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID GROUP BY DEPT_NAME ORDER BY HIGHESTAVGSALARY DESC LIMIT 1;

SELECT SALARY FROM EMPLOYEE WHERE SALARY IN(SELECT SALARY FROM EMPLOYEE GROUP BY SALARY HAVING COUNT(*)>1);

SELECT DEPARTMENT.DEPT_NAME,SUM(EMPLOYEE.SALARY) AS TOTALSALARYPAID FROM EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID GROUP BY DEPT_NAME;

SELECT EMPLOYEE.EMP_ID,DEPARTMENT.DEPT_NAME FROM EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID GROUP BY DEPT_NAME HAVING COUNT(EMP_ID)>1;

SELECT EMP_NAME,HIRE_DATE AS RECENTLYHIRED FROM EMPLOYEE ORDER BY HIRE_DATE DESC LIMIT 1;

SELECT EMP_ID,EMP_NAME,SALARY,RANK() OVER(ORDER BY SALARY DESC) AS SALARY_RANK FROM EMPLOYEE;

SELECT YEAR(HIRE_DATE) AS HIREYEAR,COUNT(*) AS EMPLOYEECOUNT FROM EMPLOYEE GROUP BY HIRE_DATE ORDER BY HIREYEAR;

SELECT * FROM EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID ORDER BY EMP_NAME;

SELECT EMP_NAME,SALARY,SALARY*0.10 AS TAX FROM EMPLOYEE;
